backend health check
- comment out unused fields in AccessToken and IdToken
- add /health endpoint to backend
- add HEALTHCHECK to backend Dockerfile
- remove handled TODOs
- set interval and retries in backend and keycloak container HEALTHCHECKs

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -40,6 +40,28 @@ COPY ./backend/resources ./resources
 # TODO define this in an env var which is read by this Dockerfile and also by main.rs
 EXPOSE 7878
 
+# How the healthcheck works, inside the container
+# exec 3<>/dev/tcp/localhost/7878 -- open a TCP connection using bash's built-in support for TCP sockets
+# echo -e "GET /health ...        -- send a GET request to the /health endpoint. The result will look like
+#
+#   HTTP/1.1 200 OK
+#   access-control-allow-credentials: true
+#   vary: origin
+#   vary: access-control-request-method
+#   vary: access-control-request-headers
+#   connection: close
+#   content-length: 0
+#
+# response=$(cat <&3)             -- save the output of file descriptor 3 to a variable called 'response'
+# exec 3>&-                       -- closes the file descriptor
+# echo "$response" | grep -q ...  -- looks for the string '200 OK' in the output, returns 1 (fails) if not found
+HEALTHCHECK --interval=1s --retries=120 CMD bash -c '\
+  exec 3<>/dev/tcp/localhost/7878 && \
+  echo -e "GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 && \
+  response=$(cat <&3); \
+  exec 3>&-; \
+  echo "$response" | grep -q "200 OK" || exit 1'
+
 ENV SUBWAY_DB_MODE="docker"
 
 # Command to run the application
